"""Make organization names strictly unique

Revision ID: 2f466f1f7bc6
Revises: dab3831cc51a
Create Date: 2026-06-02 02:13:55.969953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f466f1f7bc6'
down_revision: Union[str, None] = 'dab3831cc51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    # ### end Alembic commands ###