"""add_organization_multitenancy

Revision ID: b0eab9acad33
Revises: fe855c76e1be
Create Date: 2026-05-30 17:40:32.239640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0eab9acad33'
down_revision: Union[str, None] = 'fe855c76e1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('custom_message', sa.String(length=512), nullable=True),
    sa.Column('logo_s3_key', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'employees', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('payroll_batches', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'payroll_batches', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_batches', type_='foreignkey')
    op.drop_column('payroll_batches', 'organization_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###